config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :timelogs
  resources :activities
  devise_for :users
  resources :users
  post 'activities/update_timeframe'
  root "activities#index"
end

app/models/timelog.rb
class Timelog < ApplicationRecord
  belongs_to :user
  belongs_to :activity
end

app/controllers/timelogs_controller.rb
class TimelogsController < ApplicationController
  before_action :set_timelog, only: %i[ show edit update destroy ]

  # GET /timelogs or /timelogs.json
  def index
    @timelogs = Timelog.all
  end

  # GET /timelogs/1 or /timelogs/1.json
  def show
  end

  # GET /timelogs/new
  def new
    @timelog = Timelog.new
  end

  # GET /timelogs/1/edit
  def edit
  end

  # POST /timelogs or /timelogs.json
  def create
    @timelog = Timelog.new(timelog_params)
    @activities = Activity.all
    respond_to do |format|
      if @timelog.save
        format.turbo_stream do 
          render turbo_stream: [
            # turbo_stream.update('new_message', partial:'messages/form', locals: {message: Message.new}),
            turbo_stream.update('turbo_activities', partial:'activities/activity', locals: {timeframe: 'day' }),
          ]
        end

      else
        format.turbo_stream do 
          render turbo_stream: [
            turbo_stream.update('turbo_activities', partial:'activities/activity', locals: {timeframe: 'day' }),
          ]
        end
      end
    end
  end

  # PATCH/PUT /timelogs/1 or /timelogs/1.json
  def update
    respond_to do |format|
      if @timelog.update(timelog_params)
        format.html { redirect_to timelog_url(@timelog), notice: "Timelog was successfully updated." }
        format.json { render :show, status: :ok, location: @timelog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @timelog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timelogs/1 or /timelogs/1.json
  def destroy
    @timelog.destroy

    respond_to do |format|
      format.html { redirect_to timelogs_url, notice: "Timelog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timelog
      @timelog = Timelog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def timelog_params
      params.require(:timelog).permit(:user_id, :activity_id, :minutes, :date)
    end
end

app/helpers/timelogs_helper.rb
module TimelogsHelper
end

app/views/timelogs/_form.html.erb
<%= form_with(model: timelog, html: {class: "formaddactivity" }) do |form| %>
<div>
    <% if timelog.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(timelog.errors.count, "error") %> prohibited this timelog from being saved:</h2>

        <ul>
          <% timelog.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='d-flex justify-content-between'> 
    <i class="fa-solid fa-arrow-left mb-2" data-action="click->timelog#closeCard"
          data-timelog-payload-param = <%= current_activity.title%> > </i>
    </div>
  
    <div>
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>

    <div>
      <%= form.hidden_field :activity_id, value: current_activity.id %>
    </div>
    <div class="activity-input"> 
      <div>
      <%= form.number_field :minutes, placeholder: "Minutes", class:"activity-input-mins" %>
    </div>

    <div>
      <%= form.date_field :date, class:"activity-input-date" %>
    </div>
    </div>



    <div >
      <%= form.submit 'Add', class:"activity-submit"%>
    </div>
  </div>
<% end %>

app/views/timelogs/_timelog.html.erb
<div id="<%= dom_id timelog %>">
  <p>
    <strong>User:</strong>
    <%= timelog.user_id %>
  </p>

  <p>
    <strong>Activity:</strong>
    <%= timelog.activity_id %>
  </p>

  <p>
    <strong>Minutes:</strong>
    <%= timelog.minutes %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= timelog.date %>
  </p>

</div>

app/views/timelogs/edit.html.erb
<h1>Editing timelog</h1>

<%= render "form", timelog: @timelog %>

<br>

<div>
  <%= link_to "Show this timelog", @timelog %> |
  <%= link_to "Back to timelogs", timelogs_path %>
</div>

app/views/timelogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Timelogs</h1>

<div id="timelogs">
  <% @timelogs.each do |timelog| %>
    <%= render timelog %>
    <p>
      <%= link_to "Show this timelog", timelog %>
    </p>
  <% end %>
</div>

<%= link_to "New timelog", new_timelog_path %>

app/views/timelogs/new.html.erb
<h1>New timelog</h1>

<%= render "form", timelog: @timelog %>

<br>

<div>
  <%= link_to "Back to timelogs", timelogs_path %>
</div>

app/views/timelogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @timelog %>

<div>
  <%= link_to "Edit this timelog", edit_timelog_path(@timelog) %> |
  <%= link_to "Back to timelogs", timelogs_path %>

  <%= button_to "Destroy this timelog", @timelog, method: :delete %>
</div>