config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :timelogs
  resources :activities
  devise_for :users
  resources :users
  post 'activities/update_timeframe'
  root "activities#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  has_many :timelogs, dependent: :destroy
  
  TIMEFRAMES= [:day, :week, :month]

  def getCurrentLogs(timeframe, id)
    total = 0
    if timelogs
      logs = timelogs.where("date>?", 1.day.ago.utc ).where(user_id: id) if timeframe =='day'
      logs = timelogs.where("date>?", 1.week.ago.utc).where(user_id: id) if timeframe =='week'
      logs = timelogs.where("date>?", 1.month.ago.utc).where(user_id: id) if timeframe =='month'
      logs.map  do |log| 
        total+=log.minutes if log.minutes!= nil
      end
    end
     total > 60 ? "#{(total.to_f  / 60).round(1)} hrs" : "#{total} mins"
  end

  def getPrevLogs(timeframe, id)
    total = 0
    if timelogs
      logs = timelogs.where('date BETWEEN ? AND ?', 2.day.ago,  1.day.ago ).where(user_id: id) if timeframe == 'day'
      logs = timelogs.where('date BETWEEN ? AND ?', 2.week.ago, 1.week.ago).where(user_id: id) if timeframe == 'week'
      logs = timelogs.where('date BETWEEN ? AND ?', 2.month.ago, 1.month.ago).where(user_id: id) if timeframe == 'month'
      logs.map  do |log| 
        total+=log.minutes if log.minutes!= nil
      end
    end
     total > 60 ? "#{(total.to_f  / 60).round(1)} hrs" : "#{total} mins"
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  def update_timeframe
    @activities = Activity.all
    respond_to do |format|
      format.turbo_stream do 
        render turbo_stream: [
          turbo_stream.update('turbo_activities', partial:'activities/activity', locals: {timeframe: params[:timeframe] })
        ]
      end
    end
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    # respond_to do |format|
    #   if @activity.update(activity_params)
    #     format.html { redirect_to activity_url(@activity), notice: "Activity was successfully updated." }
    #     format.json { render :show, status: :ok, location: @activity }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @activity.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:user_id, :title, :style)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<div class="activities-innercontainer" id = "activities-innercontainer" data-controller= "timelog">
  <% @activities.each do |activity| %>

    <div class="activity-card" style="background-color: <%= activity.style %>" >
      <div >
        <%= render partial: "timelogs/form", locals:{timelog: Timelog.new, current_activity: activity } %>
      </div>
      <div class="activity-card-sec" data-timelog-target=<%= " #{activity.title.downcase}" %>> 
      <%= image_tag "icon-#{activity.title.downcase}.svg", width: '50' %>
      <div class="activity-inner">
        <div class="activity-header">
          <h4>
            <%= activity.title %>
          </h4>
          <div class="icon-container">
            <i  class="fa-solid fa-plus" 
                data-action="click->timelog#showCard"
                data-timelog-payload-param = <%= activity.title%>
                ></i>
          </div>
        </div>
        <div class="activity body">
          <h3>
            <%= activity.getCurrentLogs(timeframe, current_user.id) %>
          </h3>
        </div>
        <div class="activity-footer">
          <p>
            <%= "Last #{timeframe} - #{activity.getPrevLogs(timeframe, current_user.id)}" %>
          </p>
        </div>
      </div>
      </div>
    </div>
  <% end %>
</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<div class="activities-container">
  <div class="user-container">
    <div class="user-card">
      <div class="image-container">
        <% if current_user.image.attached? %>
          <%= image_tag current_user.image,width:'70', height: '70'  %>
        <% else %>
          <%= image_tag 'avatar.webp',width:'60'  %>
        <% end %>
      </div>
      <div> 
      <p>Report for</p>
      <h2>
        <%= current_user.getName  %>
        <br/>
        <%= current_user.lastName %>
      </h2>
      </div>
    </div>
    <div class="timeframes" >
      <% Activity::TIMEFRAMES.each do |timeframe|  %>
        <%= button_to timeframe.capitalize(), activities_update_timeframe_path(timeframe:timeframe), class:"timeframe-button" %>
      <% end %>
    </div>
  </div>
  <div id="turbo_activities">
    <%= render partial: 'activities/activity', locals: { timeframe: 'day'} %>
  </div>
</div>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity %>

<div>
  <%= link_to "Edit this activity", edit_activity_path(@activity) %> |
  <%= link_to "Back to activities", activities_path %>

  <%= button_to "Destroy this activity", @activity, method: :delete %>
</div>